#include <efi.h>
#include <efilib.h>

#ifndef DISPLAY
#define DISPLAY

#define THEME_INFO EFI_WHITE|EFI_BACKGROUND_BLACK
#define THEME_WARNING EFI_YELLOW|EFI_BACKGROUND_BLACK
#define THEME_ERROR EFI_LIGHTRED|EFI_BACKGROUND_BLACK
#define THEME_SUCCESS EFI_GREEN|EFI_BACKGROUND_BLACK

extern EFI_GRAPHICS_OUTPUT_MODE_INFORMATION* GopInfo;
UINT32 RGB(UINT8 Red,UINT8 Green,UINT8 Blue);

EFI_STATUS GopInit();
EFI_STATUS SetPixel(UINT32 Color,UINT32 x,UINT32 y);
EFI_STATUS FillDisplay(UINT32 Color);
void CPrint( UINTN color, CONST CHAR16 *fmt, ...);

#endif